# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20160823_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
