# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 14:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_eater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eater',
            name='food_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
